### ISSUE TITLE
[多来源条目] 服务端重构

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#261]
## 概述
榕典的目标是“多来源电子词典”，不过目前其实是按“单来源”写的（仅feng）。要支持其他来源（李，contrib等）之前，需要做一系列重构。

## TODOs
- [x] Indexer: Load contrib
- [x] Indexer: Load zingzeu_words
- [x] GetYngdiengDocument rpc
- [x] Indexer: Create YngdiengDocument
- [x] New details page
- [x] integrate with Lucene
- [x] Search V2 rpc
- [x] zingzeu-data: add zingzeu ID to contrib
